language: python

matrix:
    include:
        - dist: trusty
          sudo: false
          python: 2.7
        - dist: xenial
          sudo: true
          python: 3.7

install:
  - pip install poetry coveralls
  - poetry install

script: make test && make cover && coveralls